import { IProject } from '@app/models/projects';

export const PROJECTS: IProject[] = [
  {
    translatePrefix: 'blackskull-pharma',
    image: 'assets/images/projects/blackskull-pharma.png',
    link: 'https://blackskullpharma.com.br/',
    favorite: true,
    type: 'complete',
    technologies: ['Shopify', 'NextJS'],
  },
  {
    translatePrefix: 'tria-health',
    image: 'assets/images/projects/tria-health.png',
    link: 'https://tria.health/',
    favorite: true,
    type: 'complete',
    technologies: ['Angular', 'SCSS'],
  },
  {
    translatePrefix: 'marica-filmes',
    image: 'assets/images/projects/marica-filmes.png',
    link: 'https://maricafilmes.com.br/',
    favorite: true,
    type: 'complete',
    technologies: ['Angular', 'SCSS', 'Django'],
  },
  {
    translatePrefix: 'oficial-med',
    image: 'assets/images/projects/oficial-med.png',
    link: 'https://oficialmed.com.br/',
    favorite: false,
    type: 'complete',
    technologies: ['Shopify'],
  },
  {
    translatePrefix: 'portfolio-ide',
    image: 'assets/images/projects/portfolio-ide.png',
    link: 'https://dev.kaualf.com/',
    favorite: false,
    type: 'complete',
    technologies: ['Angular, SCSS'],
  },
  {
    translatePrefix: 'nip',
    image: 'assets/images/projects/nip.png',
    link: 'https://nip.imb.br/',
    favorite: false,
    type: 'complete',
    technologies: ['Angular, SCSS', 'Django', 'Analytics', 'SEO'],
  },
  {
    translatePrefix: 'new-tab',
    image: 'assets/images/projects/new-tab.png',
    link: 'https://new-tab.kaualf.com/',
    favorite: false,
    type: 'small',
    technologies: ['NextJS', 'TailwindCSS'],
  },
  {
    translatePrefix: 'bot-wpp-flow',
    image: 'assets/images/projects/bot-wpp-flow.png',
    link: 'https://github.com/kaualandi/bot-whatsapp-flow',
    favorite: false,
    type: 'small',
    technologies: ['NodeJS'],
  },
  {
    translatePrefix: 'mae-estar',
    image: 'assets/images/projects/mae-estar.png',
    link: 'https://www.maeestar.com.br/',
    favorite: false,
    type: 'complete',
    technologies: ['Angular', 'SCSS', 'Analytics'],
  },
  {
    translatePrefix: 'bruce',
    image: 'assets/images/projects/bruce.png',
    link: 'https://github.com/kaualandi/bot-whatsapp',
    favorite: false,
    type: 'small',
    technologies: ['NodeJS', 'JSON Server', 'Google APIs'],
  },
  {
    translatePrefix: 'conversation',
    image: 'assets/images/projects/conversation.png',
    link: 'https://github.com/kaualandi/conversation-form',
    favorite: false,
    type: 'small',
    technologies: ['NextJS', 'TailwindCSS', 'NextUI'],
  },
];
